        .ORIG X3300
GETI
	ST R1, SAVER1
	ST R2, SAVER2

KEYSTAT	LDI R2, KBSR		; GET KEYBOARD STATUS
	BRzp KEYSTAT		; POLL KEYBOARD
	LDI R2, KBDR		; GET THE TYPED KEY

	AND R0, R0, #0		; CLEARS R0
	ADD R0, R2, #0		; PLACES KEY INTO R0
	AND R0, R0, #15		; PLACES INTEGER IN R0

DISSTAT	LDI R1, DSR		; GET DISPLAY STATUS
	BRzp DISSTAT		; POLL DISPLAY
	STI R2, DDR		; STORE CHAR INTO DDR AND PRINT

	LD R1, SAVER1		; RESTORES R1
	LD R2, SAVER2		; RESTORES R2

	RET

SAVER1	.FILL x0000
SAVER2	.FILL x0000

KBSR	.FILL xFE00
KBDR	.FILL xFE02
DSR	.FILL xFE04
DDR	.FILL xFE06

	.END